name: 'Sync cluster to mlflow'

inputs:
  name:
    description: 'Job name'
    required: true
  host:
    description: 'Remote Host'
    required: true
  user:
    description: 'Remote User'
    required: true
  experiment_name:
    description: 'Name for experiment'
    required: true
  run_name:
    description: "Name for run"
    required: true
  url:
    description: "Mlflow tracking url"
    required: true
  task:
    description: "Mlflow task [schedule, sync, stop]"

  
runs:
  using: "composite"
  steps:
    - id: setup-python
      name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        architecture: 'x64'

    - name: Start
      if: ${{ inputs.task }} == 'start'
      run: ls ${{ github.action_path }}
        
  