name: Test mlflow action
run-name: ${{ github.actor }} is executing test mlflow action 🚀

on:
  workflow_dispatch:
  
jobs:
  test:
    env:
      JOB_PATH: /gpfs/scratch/${{ secrets.REMOTE_GROUP }}/${{ secrets.REMOTE_USER }}/jobs/${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/${{ github.run_id }}
      MLFLOW_TRACKING_SERVER_URL: https://jobs.mlflow.dev.aina.bsc.es
    runs-on: docker-apps
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup mlflow
        id: mlflow
        uses: ./
        with:
          experiment_name: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_source_path: /gpfs/scratch/bsc88/bsc088535/jobs/jupyterlab_apps/9205297804/logs #${{ env.JOB_PATH }}/logs
          traking_url: 'https://jobs.mlflow.dev.aina.bsc.es' #${{ env.MLFLOW_TRACKING_SERVER_URL }}
          run_name: 12345 
          schedule: 'true'

      - name: Get mlflow artifact url
        run: |
          echo ${{ steps.mlflow.outputs.artifact_url }}

      #- name: Sync mlflow
      #  run: |
      #    ml_flow -t sync > ${{ steps.mlflow.outputs.sync_dir }}/mlflow.log
    
