name: Test mlflow action
run-name: ${{ github.actor }} is executing test mlflow action 🚀

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          experiment_name: ${{ secrets.REMOTE_GROUP }}
          run_name: 123456 
          url: ${{ env.MLFLOW_TRACKING_SERVER_URL }}
          task: "start"
      

    